apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  {{- include "mychart.labels" . | indent 2 }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Release.Name }}