output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

# output "cluster_security_group_id" {
#   description = "Security group ids attached to the cluster control plane."
#   value       = module.eks.cluster_security_group_id
# }

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

# output "key_pair_name" {
#   description = "The key pair name."
#   value       = aws_key_pair.generated_key.key_name
# }

# output "key_pair_content" {
#   description = "Content of the key pair."
#   value       = aws_key_pair.generated_key.public_key
#}

output "region" {
  description = "AWS region."
  value       = data.aws_region.current.name
}